export default [
  'ragi flour',
  'onion',
  'ginger paste',
  'chilli',
  'curry leaves',
  'methi seeds',
  'coriander',
  'cumin',
  'salt',
  'water',
  'oil',
  'moong dal',
  'turmeric',
  'rice flour',
  'dill leaves',
  'ginger',
  'ghee',
  'vermicelli',
  'ginger garlic paste',
  'carrot',
  'cabbage',
  'capsicum',
  'sweet corn',
  'pav bhaji masala',
  'kashmiri red chilli powder',
  'paneer',
  'tomato sauce',
  'chilli sauce',
  'idli rice',
  'urad dal',
  'poha',
  'rava',
  'maida',
  'curd',
  'pepper',
  'peanut',
  'cashew',
  'mustard',
  'chana dal',
  'dried red chilli',
  'hing',
  'cooked rice',
  'lemon juice',
  'coriander seeds',
  'sesame seeds',
  'rice',
  'eno',
  'rice vermicelli',
  'mint',
  'garlic',
  'coconut',
  'star anise',
  'pod cardamom',
  'cloves',
  'cinnamon',
  'fada',
  'wheat flour',
  'garam masala',
  'cumin powder',
  'aamchur',
  'kasuri methi',
  'ajwain',
  'hot water',
  'eno fruit salt',
  'beans',
  'peas',
  'sugar',
  'besan',
  'tomato',
  'fennel',
  'coriander powder',
  'lauki',
  'milk',
  'baking soda',
  'peanut oil',
  'pickle masala',
  'raw rice',
  'tamarind',
  'jaggery',
  'sesame oil',
  'dried kashmiri red chilli',
  'green chilli',
  'asafoetida',
  'olive oil',
  'kashmiri red chili powder',
  'rolled oats',
  'idli',
  'coconut oil',
  'sona masuri rice',
  'toor dal',
  'potato',
  'kashmiri chilli powder',
  'chaat masala',
  'butter',
  'mixed herbs',
  'bread',
  'green chutney',
  'cheddar cheese',
  'bottle gourd',
  'sabudana',
  'idli rava',
  '',
  'slice bread',
  'baking powder',
  'green chilli paste',
  'thick curd',
  'bay leaf',
  'gobi',
  'basmati rice',
  'bajra atta',
  'macaroni pasta',
  'fenugreek',
  'semolina',
  'mustard seeds',
  'garlic mayonnaise',
  'mozzarella cheese',
  'lettuce leaves',
  'mustard sauce',
  'banana',
  'vanilla extract',
  'cinnamon powder',
  'chocolate chip',
  'menthe',
  'paper avalakki',
  'raisins',
  'bombay rava',
  'saffron water',
  'cardamom power',
  'moth beans',
  'jeera',
  'tamarind extract',
  'thick avalakki',
  'semiya',
  'palak',
  'corn',
  'chilli flakes',
  'penne pasta',
  'cold water',
  'soda water',
  'chana masala',
  'thin poha',
  'cup',
  'dry yeast',
  'whole cashew',
  'bansi rava',
  'red chilli powder',
  'oma',
  'kasoori methi',
  'ajwain seeds',
  'dry mango powder',
  'kashmiri red chilli',
  'walnut',
  'dates',
  'badam',
  'dry grapes',
  'pistachios',
  'ripened banana',
  'warm water',
  'honey',
  'cold milk',
  'cardamom',
  'dry coconut',
  'poppy seeds',
  'spring onion',
  'beaten rice',
  'rice rawa',
  'sour curd',
  'dosa rice',
  'dalia',
  'pudina',
  'kashmiri red chilli powder',
  'beetroot',
  'putani',
  'puttu flour',
  'fenugreek seeds',
  'ridge guard',
  'sona masuri rice.',
  'coconut milk',
  'luke water',
  'soy sauce',
  'green chili',
  'methi leaves',
  'kashmiri chili powder',
  'carrot & cucumber sandwich spread',
  'leftover chapati',
  'lettuce',
  'avocado',
  'yeast',
  'tamarind pulp',
  'puliyogare masala',
  'sambar powder',
  'spaghetti',
  'puffed rice',
  'caraway seeds',
  'brocolli',
  'sachets maggi masala',
  'maggi noodles',
  'boiled potato',
  'chili paste',
  'soda',
  'jowar flour',
  'bajra',
  'oats',
  'wheat dough',
  'pizza sauce',
  'pieces olives',
  'pieces jalapeno',
  'spinach',
  'mozzarella or cheddar cheese',
  'corn flour',
  'schezwan sauce',
  'vinegar',
  'noodles',
  'saunf',
  'channa dal',
  'thick poha',
  'red capsicum',
  'florets cauliflower',
  'cheddar',
  'bread slice',
  'cheese slice',
  'mayonnaise sauce',
  'eggless mayonnaise',
  'suji',
  'lemon',
  'sandwich bread',
  'cream cheese',
  'cucumber',
  'pepper powder',
  'chia seeds',
  'low fat milk',
  'walnuts',
  'amchur powder',
  'crumbled paneer',
  'fennel seeds',
  'dosa batter',
  'boiled vegetables',
  'coconut chutney',
  'aloo bhaji',
  'vangi bath masala powder',
  'clove',
  'whole dried kashmiri red chilli',
  'mayonnaise',
  'black cardamom',
  'groundnuts',
  'jackfruit leaves',
  'coconut leaf stick',
  'thin rice flakes',
  'almond',
  'brinjal',
  'aloo',
  'bhindi',
  'tomato puree',
  'cashew paste',
  'cream',
  'roasted gram dal',
  'florets gobi',
  'black chickpea',
  'pumpkin',
  'hung curd',
  'raw banana',
  'mushroom',
  'baby potatoes',
  'boiled potatoes',
  'almonds',
  'cauliflower',
  'suvarnagadde',
  'jeea',
  'chickpea',
  'soya bean',
  'soya chunks',
  'baby potato',
  'big bitter gourd',
  'red chilli',
  'tamarind juice',
  'rasam powder',
  'fresh',
  'baingan',
  'dried kashmiri red chili',
  'milk powder',
  'okra',
  'kashmiri red chili',
  'rajma',
  'moong sprouts',
  'panner',
  'green chilies',
  'lobia',
  'dry fenugreek leaves',
  'mango powder',
  'black chana',
  'baby corn',
  'tomato pulp',
  'kaju',
  'kokum',
  'chana',
  'tea bags',
  'ripped tomatoes',
  'crispy sev',
  'purple brinjal',
  'tamarind water',
  'kashmir red chilli powder',
  'papad',
  'mustard leaves',
  'bitter gourd',
  'whole moong dal',
  'putaani',
  'kumbalakai',
  'aloo jeera',
  'paneer bhurji gravy',
  'dal tadka',
  'boondi raita',
  'mango pickle',
  'jeera rice',
  'phulka',
  'goda masala',
  'pomegranate seeds',
  'gulla',
  'kadle bele',
  'sun dried kokum',
  'thick fresh curd',
  'raagi hittu',
  'skin ash gourd',
  'peanut powder',
  'fennel powder',
  'cashew and raisins',
  'pineapple chunks',
  'elaichi',
  'saffron',
  'jowar flour',
  'chutney',
  'yogurt',
  'radish',
  'kewra water',
  'mattu gulla',
  'toor daal',
  'raw mango',
  'radish leaves',
  'whole black urad dal',
  'kidney beans',
  'masoor dal',
  'black urad dal',
  'pomegranate peels',
  'yoghurt',
  'mango',
  'mushrooms',
  'cumin seed',
  'mace blades',
  'chilli powder',
  'pineapple',
  'ash gourd',
  'saffron milk',
  'sugar powder',
  'dried kokum',
  'biryani masala',
  'fresh cream',
  'full cream milk',
  'white peas',
  'vangi bhath masala powder',
  'bowl',
  'huruli',
  'veg stock',
  'roasted cumin powder',
  'black sesame seeds',
  'cinammon stick',
  'basil leaves',
  'chili flakes',
  'parmesan cheese',
  'basale soppu',
  'cocunut',
  'red chili powder',
  'shah jeera',
  'mace',
  'garlic paste',
  'chilli garlic sauce',
  'yellow capsicum',
  'slit green chilli',
  'bread crumbs',
  'buttermilk',
  'cornflour',
  'cardamom powder',
  'clove  garlic',
  'khus khus',
  'parotta',
  'urad flour',
  'fenugreek leaves',
  'putani powder',
  'phool makhane',
  'ginger powder',
  'cheese',
  'corn flakes',
  'dry fruits',
  'matar',
  'moong dal kachori or matar kachori',
  'tamarind chutney',
  'sev',
  'olives',
  'jalapeños',
  'oregano',
  'sweet corn kernels',
  'spring roll pastry sheets',
  'urad dal papads',
  'fine sev',
  'roasted split gram dal',
  'murmura',
  'powdered sugar',
  'hot sev',
  'bean',
  'peri peri sauce',
  'sweet potato',
  'puris',
  'mustard powder',
  'methi powder',
  'mustard oil',
  'red food colour',
  'corn flakes crumb',
  'roti',
  'jalapeno',
  'maize flour',
  'chapati',
  'set dosa batter',
  'colocasia leaves',
  'maggi masala',
  'sweet tamarind chutney',
  'maggi tastemaker',
  'maggi',
  'unsalted butter',
  'plain flour',
  'dry soya chunks',
  'toothpick',
  'sooji',
  'white sandwich bread',
  'thin poha',
  'dal',
  'pav',
  'raw plantain',
  'ribbon pakoda plate',
  'mawa',
  'milk maid',
  'khoya',
  'melon seeds',
  'horlicks',
  'rose essence',
  'cashew powder',
  'khova',
  'pitachios',
  'dark chocolate choco fills',
  'gond',
  'figs',
  'aisins',
  'pumpkin seeds',
  'dry dates',
  'nutmeg powder',
  'edible gum',
  'makhana',
  'muskmelon seeds',
  'saffron food colour',
  'silver vark',
  'chiroti rava',
  'green food colour',
  'badam & pistachios',
  'jaiphal powder',
  'orange food colour',
  'yellow food colour',
  'dry khajur',
  '­ghee',
  'instant gulab jamun mix',
  'condensed milk',
  'desiccated coconut',
  'tin',
  'rasins',
  'tutti frutti',
  'rose water',
  'full cream cows',
  'saffron threads',
  'seedless dates',
  'limestone',
  'kewda water',
  'thickened cream',
  'ice',
  'all purpose flour',
  'sweetened condensed milk',
  'rabri',
  'white sesame seeds'
];